"""empty message

Revision ID: 16a95e2350ef
Revises: d26d313234d5
Create Date: 2024-04-18 14:18:09.322304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a95e2350ef'
down_revision = 'd26d313234d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('image_id', sa.String(length=80), nullable=False),
    sa.Column('min_disk', sa.String(length=80), nullable=False),
    sa.Column('min_ram', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
