"""empty message

Revision ID: 1cacdd5f24ad
Revises: b1b87c187170
Create Date: 2024-04-16 14:35:47.124578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cacdd5f24ad'
down_revision = 'b1b87c187170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume_id', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.drop_column('volume_id')

    # ### end Alembic commands ###
