"""empty message

Revision ID: 27a6729aa924
Revises: c93b6902369b
Create Date: 2024-04-16 16:05:05.691899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27a6729aa924'
down_revision = 'c93b6902369b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subnet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('ip_version', sa.Integer(), nullable=False),
    sa.Column('cidr', sa.String(length=80), nullable=False),
    sa.Column('gateway_ip', sa.String(length=80), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('network_id', sa.String(length=160), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.String(length=80), nullable=False))
        batch_op.drop_column('network_name')
        batch_op.drop_column('subnet_name')
        batch_op.drop_column('ip_version')
        batch_op.drop_column('gateway_ip')
        batch_op.drop_column('cidr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidr', mysql.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('gateway_ip', mysql.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('ip_version', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('subnet_name', mysql.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('network_name', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('network_id')
        batch_op.drop_column('name')

    op.drop_table('subnet')
    # ### end Alembic commands ###
