"""empty message

Revision ID: 3057ee9a12ba
Revises: 49589703255e
Create Date: 2024-04-19 10:43:46.863083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3057ee9a12ba'
down_revision = '49589703255e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_pair', schema=None) as batch_op:
        batch_op.alter_column('private_key',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_pair', schema=None) as batch_op:
        batch_op.alter_column('private_key',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
