"""empty message

Revision ID: 49589703255e
Revises: a61af51cf938
Create Date: 2024-04-19 10:20:42.326563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49589703255e'
down_revision = 'a61af51cf938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_pair',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('private_key', sa.String(length=80), nullable=True),
    sa.Column('fingerprint', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('public_key', sa.TEXT(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_pair')
    # ### end Alembic commands ###
