"""empty message

Revision ID: 58c0a8c31fb1
Revises: 
Create Date: 2024-04-15 15:56:25.755101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c0a8c31fb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('network_name', sa.String(length=80), nullable=False),
    sa.Column('subnet_name', sa.String(length=80), nullable=False),
    sa.Column('ip_version', sa.Integer(), nullable=False),
    sa.Column('cidr', sa.String(length=80), nullable=False),
    sa.Column('gateway_ip', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network')
    # ### end Alembic commands ###
