"""empty message

Revision ID: 70c26b3eec52
Revises: 27a6729aa924
Create Date: 2024-04-16 16:20:03.922824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c26b3eec52'
down_revision = '27a6729aa924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=80), nullable=False))

    with op.batch_alter_table('subnet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnet', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
