"""empty message

Revision ID: 736cbe436071
Revises: 58c0a8c31fb1
Create Date: 2024-04-16 13:26:04.441706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736cbe436071'
down_revision = '58c0a8c31fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volume',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('volume_type', sa.String(length=80), nullable=True),
    sa.Column('availability_zone', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volume')
    # ### end Alembic commands ###
