"""empty message

Revision ID: a61af51cf938
Revises: b3df159e040e
Create Date: 2024-04-18 16:23:02.795719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61af51cf938'
down_revision = 'b3df159e040e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.String(length=80), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('flavor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['flavor_id'], ['flavors.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instances')
    # ### end Alembic commands ###
