"""empty message

Revision ID: aa7c2a54b43f
Revises: 70c26b3eec52
Create Date: 2024-04-16 16:26:43.261171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa7c2a54b43f'
down_revision = '70c26b3eec52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnet', schema=None) as batch_op:
        batch_op.drop_column('gateway_ip')
        batch_op.drop_column('ip_version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_version', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gateway_ip', mysql.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
