"""empty message

Revision ID: b1b87c187170
Revises: 736cbe436071
Create Date: 2024-04-16 13:36:14.609017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1b87c187170'
down_revision = '736cbe436071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('min_disk', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('min_ram', sa.Integer(), nullable=False))
        batch_op.drop_column('volume_type')
        batch_op.drop_column('availability_zone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_zone', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('volume_type', mysql.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('min_ram')
        batch_op.drop_column('min_disk')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
