"""empty message

Revision ID: b3df159e040e
Revises: dfee74a357e3
Create Date: 2024-04-18 14:57:38.676793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3df159e040e'
down_revision = 'dfee74a357e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flavors', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flavors', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
