"""empty message

Revision ID: b91f8f58af8c
Revises: 3057ee9a12ba
Create Date: 2024-04-19 11:56:03.614793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91f8f58af8c'
down_revision = '3057ee9a12ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keypair_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'network', ['network_id'], ['id'])
        batch_op.create_foreign_key(None, 'key_pair', ['keypair_id'], ['id'])
        batch_op.create_foreign_key(None, 'flavors', ['flavor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('keypair_id')

    # ### end Alembic commands ###
