"""empty message

Revision ID: c93b6902369b
Revises: 1cacdd5f24ad
Create Date: 2024-04-16 15:09:03.716448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c93b6902369b'
down_revision = '1cacdd5f24ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.drop_column('min_disk')
        batch_op.drop_column('min_ram')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_ram', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('min_disk', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
