"""empty message

Revision ID: d26d313234d5
Revises: 84d0adef0613
Create Date: 2024-04-18 12:41:31.700340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd26d313234d5'
down_revision = '84d0adef0613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnet', schema=None) as batch_op:
        batch_op.alter_column('gateway_ip',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnet', schema=None) as batch_op:
        batch_op.alter_column('gateway_ip',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
