"""empty message

Revision ID: dfee74a357e3
Revises: 16a95e2350ef
Create Date: 2024-04-18 14:56:47.760820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfee74a357e3'
down_revision = '16a95e2350ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flavors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('flavor_id', sa.String(length=80), nullable=False),
    sa.Column('ram', sa.Integer(), nullable=False),
    sa.Column('vcpus', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=80), nullable=False),
    sa.Column('is_public', sa.String(length=80), nullable=False),
    sa.Column('is_disabled', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flavors')
    # ### end Alembic commands ###
